AWSTemplateFormatVersion: "2010-09-09"
Description: Create RDS MySQL instance

Resources:
  DemoRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: demo-rds-mysql
      Engine: mysql
      EngineVersion: "8.0"
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      MasterUsername: admin
      MasterUserPassword: DemoPass123!
      BackupRetentionPeriod: 7
      PubliclyAccessible: true
      VPCSecurityGroups:
        - !Ref DemoRDSSecurityGroup
      Tags:
        - Key: Purpose
          Value: GitHubStreak

  DemoRDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow MySQL access
      VpcId: !Ref DemoVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
