AWSTemplateFormatVersion: "2010-09-09"
Description: Create CloudFront distribution for S3 bucket

Resources:
  DemoCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - DomainName: !GetAtt DemoS3Bucket.DomainName
            Id: demo-s3-origin
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: demo-s3-origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        Tags:
          - Key: Purpose
            Value: GitHubStreak

  DemoS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: demo-cloudfront-bucket
