AWSTemplateFormatVersion: "2010-09-09"
Description: Create Step Functions state machine

Resources:
  DemoStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: demo-state-machine
      RoleArn: !GetAtt DemoStateMachineRole.Arn
      DefinitionString: |
        {
          "Comment": "Demo state machine for GitHub streak",
          "StartAt": "HelloWorld",
          "States": {
            "HelloWorld": {
              "Type": "Task",
              "Resource": "${DemoLambdaFunction.Arn}",
              "End": true
            }
          }
        }
      Tags:
        - Key: Purpose
          Value: GitHubStreak

  DemoStateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: demo-stepfunctions-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSStepFunctionsFullAccess
