AWSTemplateFormatVersion: "2010-09-09"
Description: Attach bucket policy to S3 bucket

Resources:
  DemoS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: demo-streak-bucket
      Tags:
        - Key: Purpose
          Value: GitHubStreak

  DemoBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DemoS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPublicRead
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${DemoS3Bucket.Arn}/*"
