AWSTemplateFormatVersion: "2010-09-09"
Description: Create Secrets Manager secret

Resources:
  DemoSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: demo-secret
      Description: Demo secret for application credentials
      SecretString: |
        {
          "username": "admin",
          "password": "SuperSecretPass123"
        }
      Tags:
        - Key: Environment
          Value: demo
